### ISSUE TITLE
Update diffusers-interpret to work with the latest diffusers package (0.8.0)

### ISSUE THREAD

**Issue by federicotorrielli** [JoaoLages/diffusers-interpret#21]
When using diffusers-interpret with the latest diffusers (0.8.0, yes, I need this version because I use Euler discrete scheduler), it gives the following error:

`ImportError: cannot import name 'preprocess_mask' from 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint' (/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py)`

Can it be fixed to work with it? 0.3.0 is now _very_ outdated.
Thanks!

**Comment by JoaoLages** [comment]
I understand the frustration, but I tried my best to make this package compatible with `diffusers` and Hugging Face did not help.
I suggest `diffusers-interpret` users help me and write in [this Issue](https://github.com/huggingface/diffusers/issues/529) and in [this PR](https://github.com/huggingface/diffusers/pull/506), stating that they'd that `diffusers` incorporated those changes, to make packages like `diffusers-interpret` to be fully compatible for newer versions. 
Usually, the Hugging Face community helps when there is a considerable amount of people interested.

**Comment by JoaoLages** [comment]
Basically, they need to accept `text_embeddings` [in this method call](https://github.com/huggingface/diffusers/blob/44e56de9aaaa103ad11ca2953dc86ba6f64ba5d4/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L389) and also remove the `@torch.no_grad()` decorator, and this package would not depend on their minor updates.

**Comment by federicotorrielli** [comment]
I saw your PR on diffusers.. can you open two PRs for the two different problems explaining why? I will follow you there.

**Comment by JoaoLages** [comment]
To be honest, all the needed changes were made in [this PR](https://github.com/huggingface/diffusers/pull/506).
It's not worth it for me to redo the code if they have not approved it previously.
Try to comment in that PR and tag a couple of maintainers to get their attention to the lack of compatibility with packages like this 😞

**Comment by federicotorrielli** [comment]
I started writing in different PRs, let's see if they really make a change. In the meantime, it would be awesome to have a pypi diffusers package adapted to be compatibile with this but on the latest version!

**Comment by federicotorrielli** [comment]
@JoaoLages we can follow [this suggestion](https://github.com/huggingface/diffusers/issues/551#issuecomment-1330569740) and open the two feature requests.

**Comment by keturn** [comment]
@invoke-ai would also like an API that lets us provide our own text_embeddings, as it's necessary for us and anyone else who does any kind of token-weighting.

We're still in the very messy middle phase of our diffusers integration, and we haven't started trying to submit pipeline API changes like this upstream yet, but I think we'd be very much onboard for a PR or feature request for that.

As things stand at the moment, diffusers really expects an application this sophisticated will more or less completely disregard their existing `StableDiffusionPipeline` class and write their own.

There has been _some_ progress on this front, for example StableDiffusionPipeline now exposes methods like `prepare_latents` and `decode_latents` an application-specific subclass can take advantage of. But Patrick seems to really _like_ long methods and hasn't been prioritizing extensibility.

(InvokeAI is interested in adding some interpretation aids. We'll see how this goes.)

**Comment by zakrzewki** [comment]
Hi, I wanted to follow up as presented demo colab is not working at all. When downloading StableDiffusion pipeline I got error

`Fetching 33 files: 100%
33/33 [00:00<00:00, 1808.93it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-1e02d2df0a90>](https://localhost:8080/#) in <cell line: 8>()
      6 device = 'cuda' if torch.cuda.is_available() else 'cpu'
      7 
----> 8 pipe = StableDiffusionPipeline.from_pretrained(
      9     "CompVis/stable-diffusion-v1-4",
     10     use_auth_token=True,

[/usr/local/lib/python3.10/dist-packages/diffusers/pipeline_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    371                         load_method_name = importable_classes[class_name][1]
    372 
--> 373                 load_method = getattr(class_obj, load_method_name)
    374 
    375                 loading_kwargs = {}

TypeError: getattr(): attribute name must be string`

I found an error about it on SO: https://stackoverflow.com/questions/74687769/typeerror-getattr-attribute-name-must-be-string-in-pytorch-diffusers-how

Which points `diffusers` to 0.3.0.
When I tried to update it and use recent version, I got error:
`Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.9.1->diffusers-interpret) (1.3.0)
Installing collected packages: diffusers
  Attempting uninstall: diffusers
    Found existing installation: diffusers 0.24.0
    Uninstalling diffusers-0.24.0:
      Successfully uninstalled diffusers-0.24.0
Successfully installed diffusers-0.3.0
WARNING: The following packages were previously imported in this runtime:
  [diffusers]
You must restart the runtime in order to use newly installed versions.` 

When I force to use 0.24, I got error on importing explainer:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-45f27f4e1d1f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from diffusers_interpret import StableDiffusionPipelineExplainer
      2 
      3 explainer = StableDiffusionPipelineExplainer(
      4     pipe,
      5 

2 frames
[/usr/local/lib/python3.10/dist-packages/diffusers_interpret/explainers/stable_diffusion.py](https://localhost:8080/#) in <module>
      4 import torch
      5 from PIL.Image import Image
----> 6 from diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint import preprocess_mask
      7 from torch.utils.checkpoint import checkpoint
      8 from diffusers import StableDiffusionPipeline, LMSDiscreteScheduler, StableDiffusionImg2ImgPipeline, \

ImportError: cannot import name 'preprocess_mask' from 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint' (/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py)`

So I tried to install it with pip again:
`Installing collected packages: diffusers
  Attempting uninstall: diffusers
    Found existing installation: diffusers 0.24.0
    Uninstalling diffusers-0.24.0:
      Successfully uninstalled diffusers-0.24.0
Successfully installed diffusers-0.3.0
WARNING: The following packages were previously imported in this runtime:
  [diffusers]
You must restart the runtime in order to use newly installed versions.`

So I can create a pipe for stable diffusion (requires diffusers > 0.4)  OR I can use explainer (requires 0.3). Both of them does not work together in demo colab.
